server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: ecommerce
  datasource:
    url: "jdbc:mysql://localhost:3306/ecommerce"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true